name: "Release"

on:
  release:
    types: [published]

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_VERSION: "${{ github.event.release.tag_name }}"
      IMAGE_NAME: "ghcr.io/open-telemetry/demo"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: make build-docker-images
      # This workflow is provided just as an example and not for repo testing/verification
      - name: Set docker upload concurrent
        run: |
          echo $'{"max-concurrent-uploads": 1}' | sudo dd status=none of=/etc/docker/daemon.json
          sudo service docker restart
      - name: push docker image
        run: make push-docker-images
