name: "Release"

on:
  release:
    types: [published]

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      RELEASE_NAME: "${{ github.event.release.tag_name }}"
      IMAGE_REPO: "ghcr.io/wph95/demo"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: make build-docker-images
      - name: push docker image
        run: make push-docker-images
        env:
          COMPOSE_PARALLEL_LIMIT: "2"
